# mqtt模拟环境url
mqtt_environment:
  demo: demo-svc.dl-aiot.com
  test: test-svc.dl-aiot.com
  us: mqtt.us.petlibro.com
# mqtt端口号
mqtt_port: 1883
# 与代理通信之间允许的最长时间段（以秒为单位）
keepalive: 60
qos: 1

WF105_USERNAME: E5L7VNEK6BSWHS0P
WF105_PASSWD: LYUCX3O6EBQKA35DFQAABW98Y3VLT6Q2

# PLWF105测试设备SN
WF105_SN: AF010120F9CDB56FQ

# 水箱余量占比
WF105_WEIGHT_PERCENT: 80


